<#
.SYNOPSIS
  Discover a local Minecraft install and write config/local.minecraft.env (gitignored).

.DESCRIPTION
  Family/local play helper. Reuses assets already on this PC. Does not copy or
  commit Mojang/Minecraft proprietary files into the RustMC repository.
#>
[CmdletBinding()]
param(
    [string]$MinecraftDir = $(Join-Path $env:APPDATA ".minecraft"),
    [string]$OutFile = ""
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutFile) {
    $OutFile = Join-Path $repoRoot "config\local.minecraft.env"
}

if (-not (Test-Path $MinecraftDir)) {
    throw "Minecraft directory not found: $MinecraftDir"
}

$assetsDir = Join-Path $MinecraftDir "assets"
$indexesDir = Join-Path $assetsDir "indexes"
if (-not (Test-Path $indexesDir)) {
    throw "No assets/indexes under $MinecraftDir"
}

$index = Get-ChildItem $indexesDir -Filter "*.json" |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1
if (-not $index) {
    throw "No asset index JSON found in $indexesDir"
}
$assetIndexId = [System.IO.Path]::GetFileNameWithoutExtension($index.Name)

$clientJar = Get-ChildItem (Join-Path $MinecraftDir "versions") -Recurse -Filter "*.jar" -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notmatch "wrapper|installer" } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

$atmCandidates = @(
    (Join-Path $env:USERPROFILE "curseforge\minecraft\Instances\All the Mods 10 - ATM10 (1)"),
    (Join-Path $env:USERPROFILE "curseforge\minecraft\Instances\All the Mods 10 - ATM10")
)
$atmDir = $atmCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1

$objects = Join-Path $assetsDir "objects"
$objectCount = 0
if (Test-Path $objects) {
    $objectCount = (Get-ChildItem $objects -Recurse -File -ErrorAction SilentlyContinue | Measure-Object).Count
}

New-Item -ItemType Directory -Force -Path (Split-Path $OutFile) | Out-Null

$lines = @(
    "# Generated by scripts/Discover-LocalMinecraftAssets.ps1 — DO NOT COMMIT",
    "# Local/family use of an already-owned Minecraft install. Not for redistribution.",
    "MINECRAFT_DIR=$MinecraftDir",
    "MINECRAFT_ASSETS_DIR=$assetsDir",
    "MINECRAFT_ASSET_INDEX=$assetIndexId",
    "MINECRAFT_CLIENT_JAR=$($clientJar.FullName)",
    "CURSEFORGE_ATM10_DIR=$atmDir"
)
$lines | Set-Content -Encoding utf8 $OutFile

Write-Host "Wrote $OutFile"
Write-Host "  assets_dir = $assetsDir"
Write-Host "  asset_index = $assetIndexId ($objectCount object files)"
Write-Host "  client_jar  = $($clientJar.FullName)"
if ($atmDir) { Write-Host "  atm10       = $atmDir" }

# Refuse to stage proprietary paths into git if someone tries later
$forbiddenInRepo = @(
    (Join-Path $repoRoot "assets\minecraft"),
    (Join-Path $repoRoot "minecraft-assets")
)
foreach ($f in $forbiddenInRepo) {
    if (Test-Path $f) {
        Write-Warning "Proprietary-looking path exists in repo tree: $f — remove before commit"
    }
}

exit 0
